/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiSessionRouteImport } from './routes/api.session'
import { Route as ChatRoomIdRouteImport } from './routes/chat.$roomId'
import { Route as ApiChatRoomIdRouteImport } from './routes/api.chat.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomIdRoute = ChatRoomIdRouteImport.update({
  id: '/chat/$roomId',
  path: '/chat/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoomIdRoute = ApiChatRoomIdRouteImport.update({
  id: '/api/chat/$roomId',
  path: '/api/chat/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/session': typeof ApiSessionRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/api/chat/$roomId': typeof ApiChatRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/session': typeof ApiSessionRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/api/chat/$roomId': typeof ApiChatRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/session': typeof ApiSessionRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/api/chat/$roomId': typeof ApiChatRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/api/session' | '/chat/$roomId' | '/api/chat/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/session' | '/chat/$roomId' | '/api/chat/$roomId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/session'
    | '/chat/$roomId'
    | '/api/chat/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ChatRoomIdRoute: typeof ChatRoomIdRoute
  ApiChatRoomIdRoute: typeof ApiChatRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$roomId': {
      id: '/chat/$roomId'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof ChatRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$roomId': {
      id: '/api/chat/$roomId'
      path: '/api/chat/$roomId'
      fullPath: '/api/chat/$roomId'
      preLoaderRoute: typeof ApiChatRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiSessionRoute: ApiSessionRoute,
  ChatRoomIdRoute: ChatRoomIdRoute,
  ApiChatRoomIdRoute: ApiChatRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
